version: '3.8'

services:
  comms_db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - comms-db-data:/var/lib/postgresql/data
  comms_db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - comms-db-admin:/var/lib/pgadmin

volumes:
  comms-db-data:
  comms-db-admin:
