version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server/src:/usr/app/src
    env_file:
      - ./server/.env
    depends_on:
      - db
  qc_server:
    build: ./qc-server
    ports:
      - "5000:5000"
    volumes:
      - ./qc-server/src:/usr/app/src
    env_file:
      - ./qc-server/.env
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - comms-db-data:/var/lib/postgresql/data
  db_admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - comms-db-admin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  comms-db-data:
  comms-db-admin:
