export const QUICKCHAT_URL = "/quick-chat";
export const SEND_MESSAGE_EVENT = "SEND_MESSAGE";
export const QUICKCHAT_JOIN_EVENT = "QUICKCHAT_JOIN";

export const USER_JOINED_EVENT = "USER_JOINED";
export const USER_TYPING_EVENT = "USER_TYPING";
export const FETCH_PARTICIPANTS_EVENT = "FETCH_PARTICIPANTS";