export const QUICKCHAT_URL = "/quick-chat";

export const QC_SEND_MESSAGE_EVENT = "QC_SEND_MESSAGE";
export const QC_JOIN_EVENT = "QC_JOIN";
export const QC_USER_JOINED_EVENT = "QC_USER_JOINED";
export const QC_USER_TYPING_EVENT = "QC_USER_TYPING";
export const QC_FETCH_PARTICIPANTS_EVENT = "QC_FETCH_PARTICIPANTS";
export const QC_USER_LEFT_EVENT = "QC_USER_LEFT";