export const QUICKCHAT_URL = "/quick-chat";

export const SEND_MESSAGE_EVENT = "QUICKCHAT_SEND_MESSAGE";
export const QUICKCHAT_JOIN_EVENT = "QUICKCHAT_JOIN";
export const USER_JOINED_EVENT = "QUICKCHAT_USER_JOINED";
export const USER_TYPING_EVENT = "QUICKCHAT_USER_TYPING";
export const FETCH_PARTICIPANTS_EVENT = "QUICKCHAT_FETCH_PARTICIPANTS";
export const USER_LEFT_EVENT = "QUICKCHAT_USER_LEFT";